name: zenpay

services:
  backend:
    build:
      context: ../..
      dockerfile: docker/local/Dockerfile.backend
    container_name: zenpay-backend
    ports:
      - "7000:7000"
    environment:
      PORT: 7000
      ALLOWED_APP_ORIGIN: https://localhost:8080
      APP_RETURN_URI_WEB: https://localhost:8080/
    env_file: ../../example/backend/.env
    networks:
      - zenpay-net
    restart: unless-stopped

  frontend:
    build:
      context: ../..
      dockerfile: docker/local/Dockerfile.frontend
      args:
        APP_RETURN_URI_WEB: https://localhost:8080/
    container_name: zenpay-frontend
    ports:
      - "8080:8080"
    volumes:
      - ../../example/app/localhost+2.pem:/etc/nginx/certs/localhost+2.pem:ro
      - ../../example/app/localhost+2-key.pem:/etc/nginx/certs/localhost+2-key.pem:ro
    networks:
      - zenpay-net
    restart: unless-stopped
    depends_on:
      - backend

networks:
  zenpay-net:
    driver: bridge
