/**
 * Cloudflare Worker entrypoint for the zenpay-backend Docker image (see
 * ../Dockerfile). Fronts the container per Cloudflare's required
 * Worker -> Durable Object -> Container request path — there is no way for
 * a client to reach a container directly.
 */

import { Container, getContainer } from "@cloudflare/containers";

/**
 * Durable Object wrapper around the zenpay-backend container. One fixed
 * instance ("primary", see `fetch` below) serves every request — this
 * backend is a single shared service, not spun up per session/user.
 */
export class ZenpayContainer extends Container {
  /** Must match the Dockerfile's `ENV PORT` / `EXPOSE`. */
  defaultPort: number = 7000;
  /** Stops the container instance after this long with no requests. */
  sleepAfter: string = "10m";
}

export default {
  /**
   * Routes every request to the single "primary" `ZenpayContainer` instance.
   * @param request - The incoming client request.
   * @param env - Worker bindings, generated by `wrangler types` into
   *   worker-configuration.d.ts from wrangler.jsonc.
   * @returns The container's response, unmodified.
   */
  async fetch(request: Request, env: Env): Promise<Response> {
    return getContainer(env.ZENPAY_CONTAINER, "primary").fetch(request);
  },
};
