/**
 * Cloudflare Worker entrypoint fronting two containers: the zenpay-backend
 * API (see ../docker/cloudflare/Dockerfile.backend) and the Flutter Web
 * frontend served by nginx (see ../docker/cloudflare/Dockerfile.frontend) —
 * mirrors running `dart run
 * cli.dart --server` and `--web` as two separate local processes. Fronts the
 * required Worker -> Durable Object -> Container request path for each;
 * there is no way for a client to reach a container directly.
 */

import { Container, getContainer } from "@cloudflare/containers";

/**
 * Durable Object wrapper around the zenpay-backend API container. One fixed
 * instance ("primary", see `fetch` below) serves every request — this
 * backend is a single shared service, not spun up per session/user.
 */
export class ZenpayBackendContainer extends Container {
  /** Must match docker/cloudflare/Dockerfile.backend's `ENV PORT` / `EXPOSE`. */
  defaultPort: number = 7000;
  /** Stops the container instance after this long with no requests. */
  sleepAfter: string = "10m";
  /**
   * `envVars` is the only way values reach the container process — Worker
   * bindings (`vars` in wrangler.jsonc, `wrangler secret put`) populate
   * `this.env` but are NOT auto-forwarded into the container's environment.
   * Without this, example/backend/bin/server.dart finds every required var
   * missing and calls `exit(1)` before binding its port at all.
   */
  envVars = {
    ZENPAY_MERCHANT_CODE: this.env.ZENPAY_MERCHANT_CODE,
    ZENPAY_API_KEY: this.env.ZENPAY_API_KEY,
    ZENPAY_USERNAME: this.env.ZENPAY_USERNAME,
    ZENPAY_PASSWORD: this.env.ZENPAY_PASSWORD,
    TOKEN_SECRET: this.env.TOKEN_SECRET,
    PUBLIC_BASE_URL: this.env.PUBLIC_BASE_URL,
    ALLOWED_APP_ORIGIN: this.env.ALLOWED_APP_ORIGIN,
    APP_RETURN_URI_WEB: this.env.APP_RETURN_URI_WEB,
    FIREBASE_PROJECT_NUMBER: this.env.FIREBASE_PROJECT_NUMBER,
    FIREBASE_SERVICE_ACCOUNT_JSON: this.env.FIREBASE_SERVICE_ACCOUNT_JSON,
  };
}

/**
 * Durable Object wrapper around the nginx container serving the built
 * Flutter Web app. Same single-shared-instance model as
 * {@link ZenpayBackendContainer}.
 */
export class ZenpayFrontendContainer extends Container {
  /** Must match docker/cloudflare/Dockerfile.frontend's nginx `listen` / `EXPOSE`. */
  defaultPort: number = 8080;
  /** Stops the container instance after this long with no requests. */
  sleepAfter: string = "10m";
}

/**
 * Path prefixes served by the backend container — every route
 * `_buildRouter` in example/backend/lib/src/server_app.dart registers
 * outside the Flutter Web static mount. Everything else goes to the
 * frontend container.
 */
const backendPathPrefixes = ["/api/v1/", "/return", "/.well-known/"];

function isBackendPath(pathname: string): boolean {
  return backendPathPrefixes.some((prefix) => pathname === prefix || pathname.startsWith(prefix));
}

export default {
  /**
   * Routes each request to the backend or frontend container's single
   * fixed-name instance, by path.
   * @param request - The incoming client request.
   * @param env - Worker bindings, generated by `wrangler types` into
   *   worker-configuration.d.ts from wrangler.jsonc.
   * @returns The container's response, unmodified.
   */
  async fetch(request: Request, env: Env): Promise<Response> {
    const { pathname } = new URL(request.url);
    const container = isBackendPath(pathname)
      ? getContainer(env.ZENPAY_BACKEND_CONTAINER, "primary")
      : getContainer(env.ZENPAY_FRONTEND_CONTAINER, "web-1");
    return container.fetch(request);
  },
};
