// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBjBFx10SJcNSc9fdr6kVqcx3ydml0QMk',
    appId: '1:356498821161:web:a828a7eae68a936fc68c38',
    messagingSenderId: '356498821161',
    projectId: 'livecodes-43380',
    authDomain: 'livecodes-43380.firebaseapp.com',
    storageBucket: 'livecodes-43380.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAftAbHTxAGZBwVSQclNUdp5PntmW1lsys',
    appId: '1:356498821161:android:0c4280696058bb9fc68c38',
    messagingSenderId: '356498821161',
    projectId: 'livecodes-43380',
    storageBucket: 'livecodes-43380.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDftYXGLLoi5BeRDcal_U5A623zK2wTkN0',
    appId: '1:356498821161:ios:b2e58f127e5a39a4c68c38',
    messagingSenderId: '356498821161',
    projectId: 'livecodes-43380',
    storageBucket: 'livecodes-43380.firebasestorage.app',
    iosBundleId: 'au.com.zenithpayments.zenpayExampleApp',
  );
}
